Repository maxhoesel-ansible/ansible-collection-smallstep, pull requests merged in 2022-08, with the labels that each got.

#179 add Ubuntu 22 + Rocky 9 to molecule tests
  roles/step_acme_cert/README.md
  roles/step_acme_cert/molecule/default/molecule.yml
  roles/step_bootstrap_host/README.md
  roles/step_bootstrap_host/molecule/default/molecule.yml
  roles/step_ca/README.md
  roles/step_ca/molecule/default/molecule.yml
  roles/step_cli/README.md
  roles/step_cli/molecule/default/molecule.yml
Labels: ci

#181 make step-cli/ca install dir user-selectable
  CONTRIBUTING.md
  roles/step_bootstrap_host/README.md
  roles/step_bootstrap_host/defaults/main.yml
  roles/step_bootstrap_host/molecule/default/converge.yml
  roles/step_bootstrap_host/molecule/default/verify.yml
  roles/step_bootstrap_host/tasks/main.yml
  roles/step_ca/README.md
  roles/step_ca/defaults/main.yml
  roles/step_ca/vars/main.yml
  roles/step_cli/README.md
  roles/step_cli/defaults/main.yml
  roles/step_cli/molecule/default/converge.yml
  roles/step_cli/molecule/default/verify.yml
  roles/step_cli/tasks/install.yml
  roles/step_cli/vars/main.yml
Labels: pr-feature, roles

#182 replace `except` with --password-file flags
  roles/step_ca/README.md
  roles/step_ca/tasks/init.yml
  roles/step_ca/tasks/install.yml
Labels: enhancement, chore

#183 Roles: add Fedora 36 support
  roles/step_acme_cert/README.md
  roles/step_acme_cert/molecule/default/molecule.yml
  roles/step_acme_cert/molecule/default/prepare.yml
  roles/step_bootstrap_host/README.md
  roles/step_bootstrap_host/molecule/default/molecule.yml
  roles/step_bootstrap_host/molecule/default/prepare.yml
  roles/step_ca/README.md
  roles/step_ca/molecule/default/molecule.yml
  roles/step_ca/molecule/default/prepare.yml
  roles/step_ca/tasks/install.yml
  roles/step_cli/README.md
  roles/step_cli/molecule/default/molecule.yml
  roles/step_cli/molecule/default/prepare.yml
  roles/step_cli/tasks/install.yml
Labels: ci, pr-bugfix

#176 Allow local cert/key files and encrypted file
  roles/step_ca/README.md
  roles/step_ca/defaults/main.yml
  roles/step_ca/meta/argument_specs.yml
  roles/step_ca/molecule/default/files/molecule-ca.key
  roles/step_ca/molecule/default/molecule.yml
  roles/step_ca/molecule/default/prepare.yml
  roles/step_ca/tasks/check.yml
  roles/step_ca/tasks/init.yml
  roles/step_ca/vars/main.yml
Labels: pr-feature

#197 Update collection to 0.22 release
  tests/constants.sh
Labels: chore, pr-breaking
